name: hello-world

on:
  push: 
    branches: [main]
  workflow_dispatch:

jobs:
  say-hello:
    name: First Hello World
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello world"
